# Generated by Django 4.1.6 on 2023-02-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetail',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
